services:
  bizkit-database:
    container_name: bizkit-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:16.2-alpine3.19
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - bizkit-database:/var/lib/postgresql/data
    networks:
      - webnet
    restart: always

  bizkit-backend:
    container_name: bizkit-backend
    build: ./backend
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - LOGGING=${LOGGING}
      - LISTEN_PORT=${LISTEN_PORT}
    depends_on:
      bizkit-database:
        condition: service_healthy
    networks:
      - webnet
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    networks:
      - webnet
    depends_on: bizkit-backend
    restart: always

volumes:
  bizkit-database:

networks:
  webnet: